/*
 * gpsm_registers.h
 *
 *  Created on: 26 mar. 2023
 *      Author: Ludo
 */

#ifndef __GPSM_REGISTERS_H__
#define __GPSM_REGISTERS_H__

#ifndef UNA_AT_DISABLE_FLAGS_FILE
#include "una_at_flags.h"
#endif
#include "common_registers.h"
#include "types.h"
#include "una.h"

/*** GPSM REGISTERS structures ***/

/*!******************************************************************
 * \enum GPSM_register_address_t
 * \brief GPSM registers map.
 *******************************************************************/
typedef enum {
    GPSM_REGISTER_ADDRESS_CONFIGURATION_0 = COMMON_REGISTER_ADDRESS_LAST,
    GPSM_REGISTER_ADDRESS_CONFIGURATION_1,
    GPSM_REGISTER_ADDRESS_CONFIGURATION_2,
    GPSM_REGISTER_ADDRESS_CONFIGURATION_3,
    GPSM_REGISTER_ADDRESS_STATUS_1,
    GPSM_REGISTER_ADDRESS_CONTROL_1,
    GPSM_REGISTER_ADDRESS_ANALOG_DATA_1,
    GPSM_REGISTER_ADDRESS_TIME_DATA_0,
    GPSM_REGISTER_ADDRESS_TIME_DATA_1,
    GPSM_REGISTER_ADDRESS_TIME_DATA_2,
    GPSM_REGISTER_ADDRESS_GEOLOC_DATA_0,
    GPSM_REGISTER_ADDRESS_GEOLOC_DATA_1,
    GPSM_REGISTER_ADDRESS_GEOLOC_DATA_2,
    GPSM_REGISTER_ADDRESS_GEOLOC_DATA_3,
    GPSM_REGISTER_ADDRESS_LAST,
} GPSM_register_address_t;

/*** GPSM REGISTERS macros ***/

#define GPSM_NUMBER_OF_SPECIFIC_REGISTERS                       (GPSM_REGISTER_ADDRESS_LAST - COMMON_REGISTER_ADDRESS_LAST)

#define GPSM_REGISTER_CONFIGURATION_0_MASK_AAF                  0x00000001
#define GPSM_REGISTER_CONFIGURATION_0_MASK_BKFH                 0x00000002

#define GPSM_REGISTER_CONFIGURATION_1_MASK_TIME_TIMEOUT         0x0000FFFF
#define GPSM_REGISTER_CONFIGURATION_1_MASK_GEOLOC_TIMEOUT       0xFFFF0000

#define GPSM_REGISTER_CONFIGURATION_2_MASK_TP_FREQUENCY         DINFOX_REGISTER_MASK_ALL

#define GPSM_REGISTER_CONFIGURATION_3_MASK_TP_DUTY_CYCLE        0x000000FF

#define GPSM_REGISTER_STATUS_1_MASK_TFS                         0x00000001
#define GPSM_REGISTER_STATUS_1_MASK_GFS                         0x00000002
#define GPSM_REGISTER_STATUS_1_MASK_TPST                        0x00000004
#define GPSM_REGISTER_STATUS_1_MASK_PWST                        0x00000008
#define GPSM_REGISTER_STATUS_1_MASK_BKENST                      0x00000030

#define GPSM_REGISTER_CONTROL_1_MASK_TTRG                       0x00000001
#define GPSM_REGISTER_CONTROL_1_MASK_GTRG                       0x00000002
#define GPSM_REGISTER_CONTROL_1_MASK_TPEN                       0x00000004
#define GPSM_REGISTER_CONTROL_1_MASK_PWMD                       0x00000008
#define GPSM_REGISTER_CONTROL_1_MASK_PWEN                       0x00000010
#define GPSM_REGISTER_CONTROL_1_MASK_BKEN                       0x00000020

#define GPSM_REGISTER_ANALOG_DATA_1_MASK_VGPS                   0x0000FFFF
#define GPSM_REGISTER_ANALOG_DATA_1_MASK_VANT                   0xFFFF0000

#define GPSM_REGISTER_TIME_DATA_0_MASK_YEAR                     0x00FF0000
#define GPSM_REGISTER_TIME_DATA_0_MASK_MONTH                    0x00000F00
#define GPSM_REGISTER_TIME_DATA_0_MASK_DATE                     0x000000F8
#define GPSM_REGISTER_TIME_DATA_0_MASK_DAY                      0x00000007

#define GPSM_REGISTER_TIME_DATA_1_MASK_HOUR                     0x001F0000
#define GPSM_REGISTER_TIME_DATA_1_MASK_MINUTE                   0x00003F00
#define GPSM_REGISTER_TIME_DATA_1_MASK_SECOND                   0x0000003F

#define GPSM_REGISTER_TIME_DATA_2_MASK_FIX_DURATION             0x0000FFFF

#define GPSM_REGISTER_GEOLOC_DATA_0_MASK_NF                     0x80000000
#define GPSM_REGISTER_GEOLOC_DATA_0_MASK_SECOND                 0x7FFFC000
#define GPSM_REGISTER_GEOLOC_DATA_0_MASK_MINUTE                 0x00003F00
#define GPSM_REGISTER_GEOLOC_DATA_0_MASK_DEGREE                 0x000000FF

#define GPSM_REGISTER_GEOLOC_DATA_1_MASK_EF                     0x80000000
#define GPSM_REGISTER_GEOLOC_DATA_1_MASK_SECOND                 0x7FFFC000
#define GPSM_REGISTER_GEOLOC_DATA_1_MASK_MINUTE                 0x00003F00
#define GPSM_REGISTER_GEOLOC_DATA_1_MASK_DEGREE                 0x000000FF

#define GPSM_REGISTER_GEOLOC_DATA_2_MASK_ALTITUDE               0x0000FFFF

#define GPSM_REGISTER_GEOLOC_DATA_3_MASK_HDOP                   0xFFF00000
#define GPSM_REGISTER_GEOLOC_DATA_3_MASK_NSAT                   0x000F0000
#define GPSM_REGISTER_GEOLOC_DATA_3_MASK_FIX_DURATION           0x0000FFFF

/*** GPSM REGISTERS global variables ***/

#ifdef UNA_AT_USE_REGISTER_ACCESS
extern const UNA_register_access_t GPSM_REGISTER_ACCESS[GPSM_REGISTER_ADDRESS_LAST];
#endif
#ifdef UNA_AT_USE_REGISTER_ACCESS_TIMEOUT
extern const uint32_t GPSM_REGISTER_ACCESS_TIMEOUT_MS[GPSM_REGISTER_ADDRESS_LAST];
#endif
#ifdef UNA_AT_USE_REGISTER_ERROR_VALUE
extern const uint32_t GPSM_REGISTER_ERROR_VALUE[GPSM_REGISTER_ADDRESS_LAST];
#endif

#endif /* __GPSM_REGISTERS_H__ */
