/*
 * sm_registers.h
 *
 *  Created on: 16 jan. 2023
 *      Author: Ludo
 */

#ifndef __SM_REGISTERS_H__
#define __SM_REGISTERS_H__

#include "common_registers.h"

/*** SM REGISTERS structures ***/

/*!******************************************************************
 * \enum SM_register_address_t
 * \brief SM registers map.
 *******************************************************************/
typedef enum {
    SM_REGISTER_ADDRESS_CONFIGURATION_0 = COMMON_REGISTER_ADDRESS_LAST,
    SM_REGISTER_ADDRESS_CONFIGURATION_1,
    SM_REGISTER_ADDRESS_CONFIGURATION_2,
    SM_REGISTER_ADDRESS_ANALOG_DATA_1,
    SM_REGISTER_ADDRESS_ANALOG_DATA_2,
    SM_REGISTER_ADDRESS_ANALOG_DATA_3,
    SM_REGISTER_ADDRESS_DIGITAL_DATA,
    SM_REGISTER_ADDRESS_LAST,
} SM_register_address_t;

/*** SM REGISTERS macros ***/

#define SM_NUMBER_OF_SPECIFIC_REGISTERS         (SM_REGISTER_ADDRESS_LAST - COMMON_REGISTER_ADDRESS_LAST)

#define SM_REGISTER_CONFIGURATION_0_MASK_AINF   0x00000001
#define SM_REGISTER_CONFIGURATION_0_MASK_DIOF   0x00000002
#define SM_REGISTER_CONFIGURATION_0_MASK_DIGF   0x00000004

#define SM_REGISTER_CONFIGURATION_1_MASK_AI0G   0x00007FFF
#define SM_REGISTER_CONFIGURATION_1_MASK_AI0T   0x00008000
#define SM_REGISTER_CONFIGURATION_1_MASK_AI1G   0x7FFF0000
#define SM_REGISTER_CONFIGURATION_1_MASK_AI1T   0x80000000

#define SM_REGISTER_CONFIGURATION_2_MASK_AI2G   0x00007FFF
#define SM_REGISTER_CONFIGURATION_2_MASK_AI2T   0x00008000
#define SM_REGISTER_CONFIGURATION_2_MASK_AI3G   0x7FFF0000
#define SM_REGISTER_CONFIGURATION_2_MASK_AI3T   0x80000000

#define SM_REGISTER_ANALOG_DATA_1_MASK_VAIN0    0x0000FFFF
#define SM_REGISTER_ANALOG_DATA_1_MASK_VAIN1    0xFFFF0000

#define SM_REGISTER_ANALOG_DATA_2_MASK_VAIN2    0x0000FFFF
#define SM_REGISTER_ANALOG_DATA_2_MASK_VAIN3    0xFFFF0000

#define SM_REGISTER_ANALOG_DATA_3_MASK_TAMB     0x000000FF
#define SM_REGISTER_ANALOG_DATA_3_MASK_HAMB     0x0000FF00

#define SM_REGISTER_DIGITAL_DATA_MASK_DIO0      0x00000003
#define SM_REGISTER_DIGITAL_DATA_MASK_DIO1      0x0000000C
#define SM_REGISTER_DIGITAL_DATA_MASK_DIO2      0x00000030
#define SM_REGISTER_DIGITAL_DATA_MASK_DIO3      0x000000C0

#endif /* __SM_REGISTERS_H__ */
