/*
 * uhfm_registers.h
 *
 *  Created on: 31 mar. 2022
 *      Author: Ludo
 */

#ifndef __UHFM_REGISTERS_H__
#define __UHFM_REGISTERS_H__

#ifndef UNA_AT_DISABLE_FLAGS_FILE
#include "una_at_flags.h"
#endif
#include "common_registers.h"
#include "types.h"
#include "una.h"

/*** UHFM REGISTERS structures ***/

/*!******************************************************************
 * \enum UHFM_register_address_t
 * \brief UHFM registers map.
 *******************************************************************/
typedef enum {
    UHFM_REGISTER_ADDRESS_CONFIGURATION_0 = COMMON_REGISTER_ADDRESS_LAST,
    UHFM_REGISTER_ADDRESS_CONFIGURATION_1,
    UHFM_REGISTER_ADDRESS_STATUS_1,
    UHFM_REGISTER_ADDRESS_CONTROL_1,
    UHFM_REGISTER_ADDRESS_ANALOG_DATA_1,
    UHFM_REGISTER_ADDRESS_SIGFOX_EP_ID,
    UHFM_REGISTER_ADDRESS_SIGFOX_EP_KEY_0,
    UHFM_REGISTER_ADDRESS_SIGFOX_EP_KEY_1,
    UHFM_REGISTER_ADDRESS_SIGFOX_EP_KEY_2,
    UHFM_REGISTER_ADDRESS_SIGFOX_EP_KEY_3,
    UHFM_REGISTER_ADDRESS_SIGFOX_UL_PAYLOAD_0,
    UHFM_REGISTER_ADDRESS_SIGFOX_UL_PAYLOAD_1,
    UHFM_REGISTER_ADDRESS_SIGFOX_UL_PAYLOAD_2,
    UHFM_REGISTER_ADDRESS_SIGFOX_DL_PAYLOAD_0,
    UHFM_REGISTER_ADDRESS_SIGFOX_DL_PAYLOAD_1,
    UHFM_REGISTER_ADDRESS_SIGFOX_DL_PHY_CONTENT_0,
    UHFM_REGISTER_ADDRESS_SIGFOX_DL_PHY_CONTENT_1,
    UHFM_REGISTER_ADDRESS_SIGFOX_DL_PHY_CONTENT_2,
    UHFM_REGISTER_ADDRESS_SIGFOX_DL_PHY_CONTENT_3,
    UHFM_REGISTER_ADDRESS_RADIO_TEST_0,
    UHFM_REGISTER_ADDRESS_RADIO_TEST_1,
    UHFM_REGISTER_ADDRESS_LAST,
} UHFM_register_address_t;

/*** UHFM REGISTERS macros ***/

#define UHFM_NUMBER_OF_SPECIFIC_REGISTERS               (UHFM_REGISTER_ADDRESS_LAST - COMMON_REGISTER_ADDRESS_LAST)

#define UHFM_REGISTER_CONFIGURATION_0_MASK_RC           0x0000000F
#define UHFM_REGISTER_CONFIGURATION_0_MASK_BR           0x00000030
#define UHFM_REGISTER_CONFIGURATION_0_MASK_NFR          0x000000C0
#define UHFM_REGISTER_CONFIGURATION_0_MASK_TX_POWER     0x0000FF00

#define UHFM_REGISTER_CONFIGURATION_1_MASK_TCONF        0xFFFF0000
#define UHFM_REGISTER_CONFIGURATION_1_MASK_TIFU         0x0000FFFF

#define UHFM_REGISTER_CONTROL_1_MASK_STRG               0x00000001
#define UHFM_REGISTER_CONTROL_1_MASK_TTRG               0x00000002
#define UHFM_REGISTER_CONTROL_1_MASK_CWEN               0x00000004
#define UHFM_REGISTER_CONTROL_1_MASK_RSEN               0x00000008
#define UHFM_REGISTER_CONTROL_1_MASK_CMSG               0x00010000
#define UHFM_REGISTER_CONTROL_1_MASK_MSGT               0x000E0000
#define UHFM_REGISTER_CONTROL_1_MASK_BF                 0x00100000
#define UHFM_REGISTER_CONTROL_1_MASK_UL_PAYLOAD_SIZE    0x03E00000
#define UHFM_REGISTER_CONTROL_1_MASK_RFP_TEST_MODE      0x3C000000

#define UHFM_REGISTER_STATUS_1_MASK_MESSAGE_STATUS      0x000000FF
#define UHFM_REGISTER_STATUS_1_MASK_DL_RSSI             0x0000FF00
#define UHFM_REGISTER_STATUS_1_MASK_BIDIRECTIONAL_MC    0x0FFF0000

#define UHFM_REGISTER_ANALOG_DATA_1_MASK_VRF_TX         0x0000FFFF
#define UHFM_REGISTER_ANALOG_DATA_1_MASK_VRF_RX         0xFFFF0000

#define UHFM_REGISTER_RADIO_TEST_0_MASK_RF_FREQUENCY    DINFOX_REGISTER_MASK_ALL

#define UHFM_REGISTER_RADIO_TEST_1_MASK_TX_POWER        0x000000FF
#define UHFM_REGISTER_RADIO_TEST_1_MASK_RSSI            0x0000FF00

/*** UHFM REGISTERS global variables ***/

#ifdef UNA_AT_USE_REGISTER_ACCESS
extern const UNA_register_access_t UHFM_REGISTER_ACCESS[UHFM_REGISTER_ADDRESS_LAST];
#endif
#ifdef UNA_AT_USE_REGISTER_ACCESS_TIMEOUT
extern const uint32_t UHFM_REGISTER_ACCESS_TIMEOUT_MS[UHFM_REGISTER_ADDRESS_LAST];
#endif
#ifdef UNA_AT_USE_REGISTER_ERROR_VALUE
extern const uint32_t UHFM_REGISTER_ERROR_VALUE[UHFM_REGISTER_ADDRESS_LAST];
#endif

#endif /* __UHFM_REGISTERS_H__ */
