/*
 * mpmcm_registers.c
 *
 *  Created on: 15 dec. 2024
 *      Author: Ludo
 */

#include "mpmcm_registers.h"

#include "common_registers.h"
#include "types.h"
#include "una.h"
#include "una_at.h"

/*** MPMCM REGISTERS local macros ***/

#define MPMCM_DATA_REGISTER_ACCESS \
    UNA_REGISTER_ACCESS_READ_ONLY, \
    UNA_REGISTER_ACCESS_READ_ONLY,

#define MPMCM_CHANNEL_REGISTER_ACCESS \
    MPMCM_DATA_REGISTER_ACCESS        \
    MPMCM_DATA_REGISTER_ACCESS        \
    MPMCM_DATA_REGISTER_ACCESS        \
    MPMCM_DATA_REGISTER_ACCESS        \
    MPMCM_DATA_REGISTER_ACCESS        \
    UNA_REGISTER_ACCESS_READ_ONLY,    \

#define MPMCM_CHANNEL_REGISTER_ACCESS_TIMEOUT_MS \
    /* Active power */ \
    UNA_AT_DEFAULT_TIMEOUT_MS, \
    UNA_AT_DEFAULT_TIMEOUT_MS, \
    /* RMS voltage */ \
    UNA_AT_DEFAULT_TIMEOUT_MS, \
    UNA_AT_DEFAULT_TIMEOUT_MS, \
    /* RMS current */ \
    UNA_AT_DEFAULT_TIMEOUT_MS, \
    UNA_AT_DEFAULT_TIMEOUT_MS, \
    /* Apparent power */ \
    UNA_AT_DEFAULT_TIMEOUT_MS, \
    UNA_AT_DEFAULT_TIMEOUT_MS, \
    /* Power factor */ \
    UNA_AT_DEFAULT_TIMEOUT_MS, \
    UNA_AT_DEFAULT_TIMEOUT_MS, \
    /* Energy */ \
    UNA_AT_DEFAULT_TIMEOUT_MS, \

#define MPMCM_CHANNEL_REGISTER_ERROR_VALUE \
    /* Active power */ \
    ((UNA_ELECTRICAL_POWER_ERROR_VALUE << 16) | (UNA_ELECTRICAL_POWER_ERROR_VALUE << 0)), \
    ((UNA_ELECTRICAL_POWER_ERROR_VALUE << 16) | (UNA_ELECTRICAL_POWER_ERROR_VALUE << 0)), \
    /* RMS voltage */ \
    (uint32_t) ((UNA_VOLTAGE_ERROR_VALUE << 16) | (UNA_VOLTAGE_ERROR_VALUE << 0)), \
    (uint32_t) ((UNA_VOLTAGE_ERROR_VALUE << 16) | (UNA_VOLTAGE_ERROR_VALUE << 0)), \
    /* RMS current */ \
    (uint32_t) ((UNA_CURRENT_ERROR_VALUE << 16) | (UNA_CURRENT_ERROR_VALUE << 0)), \
    (uint32_t) ((UNA_CURRENT_ERROR_VALUE << 16) | (UNA_CURRENT_ERROR_VALUE << 0)), \
    /* Apparent power */ \
    ((UNA_ELECTRICAL_POWER_ERROR_VALUE << 16) | (UNA_ELECTRICAL_POWER_ERROR_VALUE << 0)), \
    ((UNA_ELECTRICAL_POWER_ERROR_VALUE << 16) | (UNA_ELECTRICAL_POWER_ERROR_VALUE << 0)), \
    /* Power factor */ \
    ((UNA_POWER_FACTOR_ERROR_VALUE << 16) | (UNA_POWER_FACTOR_ERROR_VALUE << 0)), \
    ((UNA_POWER_FACTOR_ERROR_VALUE << 16) | (UNA_POWER_FACTOR_ERROR_VALUE << 0)), \
    /* Energy */ \
    ((UNA_ELECTRICAL_ENERGY_ERROR_VALUE << 16) | (UNA_ELECTRICAL_ENERGY_ERROR_VALUE << 0)), \

/*** MPMCM REGISTERS global variables ***/

#ifdef UNA_AT_USE_REGISTER_ACCESS
const UNA_register_access_t MPMCM_REGISTER_ACCESS[MPMCM_REGISTER_ADDRESS_LAST] = {
    COMMON_REGISTER_ACCESS
    UNA_REGISTER_ACCESS_READ_ONLY,
    UNA_REGISTER_ACCESS_READ_ONLY,
    UNA_REGISTER_ACCESS_READ_WRITE,
    UNA_REGISTER_ACCESS_READ_WRITE,
    UNA_REGISTER_ACCESS_READ_WRITE,
    UNA_REGISTER_ACCESS_READ_WRITE,
    UNA_REGISTER_ACCESS_READ_ONLY,
    UNA_REGISTER_ACCESS_READ_WRITE,
    MPMCM_DATA_REGISTER_ACCESS
    MPMCM_CHANNEL_REGISTER_ACCESS
    MPMCM_CHANNEL_REGISTER_ACCESS
    MPMCM_CHANNEL_REGISTER_ACCESS
    MPMCM_CHANNEL_REGISTER_ACCESS
    MPMCM_CHANNEL_REGISTER_ACCESS
};
#endif
#ifdef UNA_AT_USE_REGISTER_ACCESS_TIMEOUT
const uint32_t MPMCM_REGISTER_ACCESS_TIMEOUT_MS[MPMCM_REGISTER_ADDRESS_LAST] = {
    COMMON_REGISTER_ACCESS_TIMEOUT_MS
    UNA_AT_DEFAULT_TIMEOUT_MS,
    UNA_AT_DEFAULT_TIMEOUT_MS,
    UNA_AT_DEFAULT_TIMEOUT_MS,
    UNA_AT_DEFAULT_TIMEOUT_MS,
    UNA_AT_DEFAULT_TIMEOUT_MS,
    UNA_AT_DEFAULT_TIMEOUT_MS,
    UNA_AT_DEFAULT_TIMEOUT_MS,
    5000,
    UNA_AT_DEFAULT_TIMEOUT_MS,
    UNA_AT_DEFAULT_TIMEOUT_MS,
    MPMCM_CHANNEL_REGISTER_ACCESS_TIMEOUT_MS
    MPMCM_CHANNEL_REGISTER_ACCESS_TIMEOUT_MS
    MPMCM_CHANNEL_REGISTER_ACCESS_TIMEOUT_MS
    MPMCM_CHANNEL_REGISTER_ACCESS_TIMEOUT_MS
    MPMCM_CHANNEL_REGISTER_ACCESS_TIMEOUT_MS
};
#endif
#ifdef UNA_AT_USE_REGISTER_ERROR_VALUE
const uint32_t MPMCM_REGISTER_ERROR_VALUE[MPMCM_REGISTER_ADDRESS_LAST] = {
    COMMON_REGISTER_ERROR_VALUE
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
    (uint32_t) ((UNA_MAINS_FREQUENCY_ERROR_VALUE << 16) | (UNA_MAINS_FREQUENCY_ERROR_VALUE << 0)),
    (uint32_t) ((UNA_MAINS_FREQUENCY_ERROR_VALUE << 16) | (UNA_MAINS_FREQUENCY_ERROR_VALUE << 0)),
    MPMCM_CHANNEL_REGISTER_ERROR_VALUE
    MPMCM_CHANNEL_REGISTER_ERROR_VALUE
    MPMCM_CHANNEL_REGISTER_ERROR_VALUE
    MPMCM_CHANNEL_REGISTER_ERROR_VALUE
    MPMCM_CHANNEL_REGISTER_ERROR_VALUE
};
#endif
