/*
 * sm_registers.c
 *
 *  Created on: 15 dec. 2024
 *      Author: Ludo
 */

#include "sm_registers.h"

#include "common_registers.h"
#include "types.h"
#include "una.h"
#include "una_at.h"

/*** SM REGISTERS global variables ***/

#ifdef UNA_AT_USE_REGISTER_ACCESS
const UNA_register_access_t SM_REGISTER_ACCESS[SM_REGISTER_ADDRESS_LAST] = {
    COMMON_REGISTER_ACCESS
    UNA_REGISTER_ACCESS_READ_ONLY,
    UNA_REGISTER_ACCESS_READ_ONLY,
    UNA_REGISTER_ACCESS_READ_ONLY,
    UNA_REGISTER_ACCESS_READ_ONLY,
    UNA_REGISTER_ACCESS_READ_ONLY,
    UNA_REGISTER_ACCESS_READ_ONLY,
    UNA_REGISTER_ACCESS_READ_ONLY
};
#endif
#ifdef UNA_AT_USE_REGISTER_ACCESS_TIMEOUT
const uint32_t SM_REGISTER_ACCESS_TIMEOUT_MS[SM_REGISTER_ADDRESS_LAST] = {
    COMMON_REGISTER_ACCESS_TIMEOUT_MS
    UNA_AT_DEFAULT_TIMEOUT_MS,
    UNA_AT_DEFAULT_TIMEOUT_MS,
    UNA_AT_DEFAULT_TIMEOUT_MS,
    UNA_AT_DEFAULT_TIMEOUT_MS,
    UNA_AT_DEFAULT_TIMEOUT_MS,
    UNA_AT_DEFAULT_TIMEOUT_MS,
    UNA_AT_DEFAULT_TIMEOUT_MS
};
#endif
#ifdef UNA_AT_USE_REGISTER_ERROR_VALUE
const uint32_t SM_REGISTER_ERROR_VALUE[SM_REGISTER_ADDRESS_LAST] = {
    COMMON_REGISTER_ERROR_VALUE
    0x00000000,
    0x00000000,
    0x00000000,
    (uint32_t) ((UNA_VOLTAGE_ERROR_VALUE << 16) | (UNA_VOLTAGE_ERROR_VALUE << 0)),
    (uint32_t) ((UNA_VOLTAGE_ERROR_VALUE << 16) | (UNA_VOLTAGE_ERROR_VALUE << 0)),
    (uint32_t) ((UNA_HUMIDITY_ERROR_VALUE << 8) | (UNA_TEMPERATURE_ERROR_VALUE << 0)),
    ((UNA_BIT_ERROR << 6) | (UNA_BIT_ERROR << 4) | (UNA_BIT_ERROR << 2) | (UNA_BIT_ERROR << 0)),
};
#endif
